---
env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/no-unresolved: 0
  no-param-reassign: 0
  react/no-array-index-key: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
